version: '3'

services:
  app_server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tp2_host
    ports:
      - "8081:80"
  db_server:
    build:
      context: ./DevOps.db
      dockerfile: Dockerfile
    container_name: tp2_host_db
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_AGENT_ENABLED=${MSSQL_AGENT_ENABLED}
    ports:
      - "1433:1433"
    volumes:
      - ./DevOps.db:c:\docker-data